version: '2'
services:
  ipfs:
    image: "ipfs/go-ipfs:latest"
    command: "daemon --enable-pubsub-experiment"
    volumes:
      - "/var/tmp/ipfs/export:/export"
      - "/var/tmp/ipfs/data:/data/ipfs"
    ports:
      - "4001:4001"
      - "8081:8080"
      - "5001:5001"
  pepenet:
    build: .
    ports:
     - "8080:8000"
    environment:
      - IPFS_HOST=ipfs
    depends_on:
      - ipfs
